version: "3.5"

services:
  nginx:
    container_name: fontend_nginx
    build:
      context: ./
      dockerfile: ./docker/docker_nginx
    ports:
      - 80:80
    networks:
      - proxynet

networks:
  proxynet:
    name: proxynet_network
